name: Test Docker

# Only trigger, when the build workflow succeeded
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      name: Checkout
     
    - name: Build and Test
      run: |
        docker-compose -f docker-compose.yml -f docker-compose.build.yml build --build-arg TEST_BUILD=ON
        docker-compose -f docker-compose.yml -f docker-compose.build.yml up -d
        sleep 20
        docker-compose exec -T webapp /webodm/webodm.sh test
